[package]
name = "cl3"
version = "0.1.0"
authors = ["Ken Barker <ken.barker@via-technology.aero>"]
description = "A Rust implementation of the Khronos OpenCL 3.0 API."
license = "Apache-2.0"
edition = "2018"

[features]

CL_VERSION_1_1 = []
CL_VERSION_1_2 = []
CL_VERSION_2_0 = []
CL_VERSION_2_1 = []
CL_VERSION_2_2 = []
CL_VERSION_3_0 = []

# Default features:
default = ["CL_VERSION_1_2", "CL_VERSION_2_0"]

[dependencies]
libc = "0.2"
