name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Load OpenCL
      run: |
        sudo add-apt-repository ppa:intel-opencl/intel-opencl
        sudo apt-get update
        sudo apt-get install intel-opencl ocl-icd-opencl-dev
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test -- --test-threads=1
